# Serving HTML through API Gateway for AWS Lambda
service: redirector

custom:
  bucket: redirector-923798357 # change name

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  environment:
    BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

functions:
  redirect:
    handler: lib/handlers.redirect
    events:
      - http:
          method: get
          path: /
      - http:
          method: get
          path: /{any+}

resources:
  Resources:
    redirect:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
